apiVersion: v1
kind: Pod
metadata:
  name: online-inference-probes
  namespace: made
  labels:
    app: online-inference
spec:
  containers:
    - image: voiteshonok/online_inference:v6
      name: online-inference
      ports:
        - containerPort: 8000
      resources:
        requests:
          memory: "1Gi"
          cpu: "200m"
        limits:
          memory: "4Gi"
          cpu: "500m"
      readinessProbe:
        httpGet:
          path: /health
          port: 8000
        initialDelaySeconds: 15
        periodSeconds: 5
      livenessProbe:
        httpGet:
          path: /health
          port: 8000
        initialDelaySeconds: 60
        periodSeconds: 10
