apiVersion: v1
kind: Pod
metadata:
  name: online-inference-res
  namespace: made
  labels:
    app: online-inference
spec:
  containers:
    - image: voiteshonok/online_inference:v5
      name: online-inference
      ports:
        - containerPort: 8000
      resources:
        requests:
          memory: "1Gi"
          cpu: "200m"
        limits:
          memory: "4Gi"
          cpu: "500m"
