apiVersion: apps/v1
kind: Deployment
metadata:
  name: online-inference
  namespace: made
  labels:
    app: online-inference
spec:
  replicas: 8
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 8
      maxUnavailable: 8
  selector:
    matchLabels:
      app: online-inference
  template:
    metadata:
      name: online-inference
      namespace: made
      labels:
        app: online-inference
    spec:
      containers:
        - image: voiteshonok/online_inference:v5
          name: online-inference
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "1Gi"
              cpu: "200m"
            limits:
              memory: "4Gi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 10
