# @package _group_
random_seed: 42
input_data_path: "data/raw/archive.zip"
eda_dir: "reports/eda"
target_name: "target"
track:
  track_experiment: True
  experiment_data_dir: "reports/experiments"
  save_model_weights: True
  metrics_file_name: "metrics.yaml"
  config_file_name: "config.yaml"
  model_weights_file_name: "model.pickle"
  experiment_dir_name_format: "%d_%m_%Y_%H_%M_%S"