# @package _group_
input_data_path: ${main.input_data_path}
report_dir: ${main.eda_dir}
report_file_name: "eda_pandas_profiling.html"
eda_class:
  _target_: pandas_profiling.ProfileReport
  title: "Pandas Profiling Report"
  explorative: True